name: Build StreamAwesome

on:
 workflow_dispatch:
 push:
 pull_request:
  types: [opened, synchronize, reopened]

env:
  FONTAWESOME_VERSION: "6.6.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Download FontAwesome 📦
        run: |
          mkdir -p StreamAwesome/fonts/fontawesome
          wget https://use.fontawesome.com/releases/v${{ env.FONTAWESOME_VERSION }}/fontawesome-free-${{ env.FONTAWESOME_VERSION }}-web.zip -O fontawesome.zip
          unzip fontawesome.zip
          cp -r fontawesome-free-${{ env.FONTAWESOME_VERSION }}-web/css StreamAwesome/fonts/fontawesome/
          cp -r fontawesome-free-${{ env.FONTAWESOME_VERSION }}-web/webfonts StreamAwesome/fonts/fontawesome/
          rm -rf fontawesome.zip fontawesome-free-${{ env.FONTAWESOME_VERSION }}-web
      
      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install and Build 🔧
        working-directory: StreamAwesome
        run: |
          npm install
          npm run build
