name: Build StreamAwesome

on:
 workflow_dispatch:
 push:
 pull_request:
  types: [opened, synchronize, reopened]

env:
  FONTAWESOME_VERSION: "6.6.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Clone Font Awesome Overwrites ✌️
        env: 
          repoToken: ${{ secrets.TOKEN }}
        if: ${{ env.repoToken != '' }}
        uses: actions/checkout@v4
        with:
          repository: sebinside/StreamAwesome-Overwrites
          persist-credentials: false
          path: StreamAwesome/fonts
          ref: 'main'
          token: ${{ secrets.TOKEN }}

      - name: Download FontAwesome 📦
        env: 
          repoToken: ${{ secrets.TOKEN }}
        if: ${{ env.repoToken == '' }}
        run: |
          mkdir -p StreamAwesome/fonts/fontawesome
          wget https://use.fontawesome.com/releases/v${{ env.FONTAWESOME_VERSION }}/fontawesome-free-${{ env.FONTAWESOME_VERSION }}-web.zip -O fontawesome.zip
          unzip fontawesome.zip
          cp -r fontawesome-free-${{ env.FONTAWESOME_VERSION }}-web/css StreamAwesome/fonts/fontawesome/
          cp -r fontawesome-free-${{ env.FONTAWESOME_VERSION }}-web/webfonts StreamAwesome/fonts/fontawesome/
          rm -rf fontawesome.zip fontawesome-free-${{ env.FONTAWESOME_VERSION }}-web
      
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install and Build 🔧
        working-directory: StreamAwesome
        run: |
          yarn install
          yarn run build
