name: Build and Deploy StreamAwesome

on:
 workflow_dispatch:
 push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Clone Font Awesome Overwrites ✌️
        uses: actions/checkout@v4
        with:
          repository: sebinside/StreamAwesome-Overwrites
          path: StreamAwesome/fonts
          ref: 'main'
          token: ${{ secrets.TOKEN }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install and Build 🔧
        working-directory: StreamAwesome
        run: |
          yarn install
          yarn run build

      - name: Deploy 🚀
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: StreamAwesome/dist/
          remote_path: /home/${{ secrets.USERNAME }}/html/${{ vars.TARGET }}
          remote_host: ${{ secrets.SERVER }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.PRIVATE_KEY }}
